language: node_js

sudo: false

node_js:
  - '5'

cache:
  directories:
    - node_modules

before_install:
  - npm install -g gulp-cli

install:
  - npm install
  - npm run release

script:
  - npm test
